name: Linux_Container_DOTNET_Core_Workflow

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout Github Action' 
      uses: actions/checkout@master
    
    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - uses: azure/docker-login@v1
      with:
        login-server: beetlejuice.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t beetlejuice.azurecr.io/azuredeploytest:${{ github.sha }} -f ./TestApp/Dockerfile
        docker push beetlejuice.azurecr.io/azuredeploytest:${{ github.sha }} 
      
    - name: Azure WebApp Container
      uses: Azure/webapps-container-deploy@v1
      with:
        app-name: 'test-beetlejuice-app'
        # Specify the fully qualified container image(s) name. For example, 'myregistry.azurecr.io/nginx:latest' or 'python:3.7.2-alpine/'. For multi-container scenario multiple container image names can be provided (multi-line separated)
        images: beetlejuice.azurecr.io/azuredeploytest:${{ github.sha }}
    
    - name: Azure logout
      run: |
        az logout
